@include('partials.head')
<body>
    <header>
        @include('partials.header')
    </header>
    <main>
        <section>
            @include('partials.jumbotron')
        </section>
        <section>
            @include('partials.thumbBox')
        </section>
        <section>
            @include('partials.bluenav')
        </section>
        <section>
            @include('partials.prefooter')
        </section>
    </main>
    <footer>
        @include('partials.footer')
    </footer>
</body>
</html>